/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by vite-plugin-uni-pages

interface NavigateToOptions {
  url: "pages/index/index" |
       "pages/demo/basic/button/index" |
       "pages/demo/basic/cell/index" |
       "pages/demo/basic/configprovider/index" |
       "pages/demo/basic/icon/index" |
       "pages/demo/basic/overlay/index" |
       "pages/demo/basic/popup/index" |
       "pages/demo/basic/transition/index" |
       "pages/demo/bingo/dollmachine/index" |
       "pages/demo/bingo/giftbox/index" |
       "pages/demo/bingo/hiteggs/index" |
       "pages/demo/bingo/marquee/index" |
       "pages/demo/bingo/shakedice/index" |
       "pages/demo/bingo/turntable/index" |
       "pages/demo/business/address/index" |
       "pages/demo/business/addresslist/index" |
       "pages/demo/business/barrage/index" |
       "pages/demo/business/card/index" |
       "pages/demo/business/category/index" |
       "pages/demo/business/comment/index" |
       "pages/demo/business/ecard/index" |
       "pages/demo/business/invoice/index" |
       "pages/demo/business/signature/index" |
       "pages/demo/business/sku/index" |
       "pages/demo/business/timeselect/index" |
       "pages/demo/dentry/calendar/index" |
       "pages/demo/dentry/cascader/index" |
       "pages/demo/dentry/checkbox/index" |
       "pages/demo/dentry/codeinput/index" |
       "pages/demo/dentry/datepicker/index" |
       "pages/demo/dentry/form/index" |
       "pages/demo/dentry/input/index" |
       "pages/demo/dentry/inputnumber/index" |
       "pages/demo/dentry/numberkeyboard/index" |
       "pages/demo/dentry/picker/index" |
       "pages/demo/dentry/radio/index" |
       "pages/demo/dentry/range/index" |
       "pages/demo/dentry/rate/index" |
       "pages/demo/dentry/searchbar/index" |
       "pages/demo/dentry/shortpassword/index" |
       "pages/demo/dentry/textarea/index" |
       "pages/demo/dentry/uploader/index" |
       "pages/demo/exhibition/animate/index" |
       "pages/demo/exhibition/avatar/index" |
       "pages/demo/exhibition/badge/index" |
       "pages/demo/exhibition/circleprogress/index" |
       "pages/demo/exhibition/collapse/index" |
       "pages/demo/exhibition/countdown/index" |
       "pages/demo/exhibition/countup/index" |
       "pages/demo/exhibition/ellipsis/index" |
       "pages/demo/exhibition/empty/index" |
       "pages/demo/exhibition/imagepreview/index" |
       "pages/demo/exhibition/list/index" |
       "pages/demo/exhibition/loadingpage/index" |
       "pages/demo/exhibition/noticebar/index" |
       "pages/demo/exhibition/popover/index" |
       "pages/demo/exhibition/price/index" |
       "pages/demo/exhibition/progress/index" |
       "pages/demo/exhibition/skeleton/index" |
       "pages/demo/exhibition/steps/index" |
       "pages/demo/exhibition/swiper/index" |
       "pages/demo/exhibition/table/index" |
       "pages/demo/exhibition/tag/index" |
       "pages/demo/exhibition/tour/index" |
       "pages/demo/exhibition/trendarrow/index" |
       "pages/demo/exhibition/watermark/index" |
       "pages/demo/feedback/actionsheet/index" |
       "pages/demo/feedback/backtop/index" |
       "pages/demo/feedback/dialog/index" |
       "pages/demo/feedback/drag/index" |
       "pages/demo/feedback/infiniteloading/index" |
       "pages/demo/feedback/notify/index" |
       "pages/demo/feedback/swipe/index" |
       "pages/demo/feedback/switch/index" |
       "pages/demo/feedback/toast/index" |
       "pages/demo/layout/divider/index" |
       "pages/demo/layout/grid/index" |
       "pages/demo/layout/layout/index" |
       "pages/demo/layout/safearea/index" |
       "pages/demo/layout/sticky/index" |
       "pages/demo/nav/elevator/index" |
       "pages/demo/nav/fixednav/index" |
       "pages/demo/nav/indicator/index" |
       "pages/demo/nav/menu/index" |
       "pages/demo/nav/navbar/index" |
       "pages/demo/nav/pagination/index" |
       "pages/demo/nav/sidenavbar/index" |
       "pages/demo/nav/tabbar/index" |
       "pages/demo/nav/tabs/index";
}
interface RedirectToOptions extends NavigateToOptions {}

interface SwitchTabOptions {
  
}

type ReLaunchOptions = NavigateToOptions | SwitchTabOptions;

declare interface Uni {
  navigateTo(options: UniNamespace.NavigateToOptions & NavigateToOptions): void;
  redirectTo(options: UniNamespace.RedirectToOptions & RedirectToOptions): void;
  switchTab(options: UniNamespace.SwitchTabOptions & SwitchTabOptions): void;
  reLaunch(options: UniNamespace.ReLaunchOptions & ReLaunchOptions): void;
}
