// For this project development
import '@vue/runtime-core'

declare module '@vue/runtime-core' {
  // GlobalComponents for Volar
  export interface GlobalComponents {
    NutActionSheet: typeof import('./components/actionsheet/actionsheet.vue')['default']
    NutAddress: typeof import('./components/address/address.vue')['default']
    NutAddressList: typeof import('./components/addresslist/addresslist.vue')['default']
    NutAnimate: typeof import('./components/animate/animate.vue')['default']
    NutAvatar: typeof import('./components/avatar/avatar.vue')['default']
    NutAvatarGroup: typeof import('./components/avatargroup/avatargroup.vue')['default']
    NutBacktop: typeof import('./components/backtop/backtop.vue')['default']
    NutBadge: typeof import('./components/badge/badge.vue')['default']
    NutBarrage: typeof import('./components/barrage/barrage.vue')['default']
    NutButton: typeof import('./components/button/button.vue')['default']
    NutCalendar: typeof import('./components/calendar/calendar.vue')['default']
    NutCard: typeof import('./components/card/card.vue')['default']
    NutCascader: typeof import('./components/cascader/cascader.vue')['default']
    NutCategory: typeof import('./components/category/category.vue')['default']
    NutCategoryPane: typeof import('./components/categorypane/categorypane.vue')['default']
    NutCell: typeof import('./components/cell/cell.vue')['default']
    NutCellGroup: typeof import('./components/cellgroup/cellgroup.vue')['default']
    NutCheckbox: typeof import('./components/checkbox/checkbox.vue')['default']
    NutCheckboxGroup: typeof import('./components/checkboxgroup/checkboxgroup.vue')['default']
    NutCircleProgress: typeof import('./components/circleprogress/circleprogress.vue')['default']
    NutCol: typeof import('./components/col/col.vue')['default']
    NutCollapse: typeof import('./components/collapse/collapse.vue')['default']
    NutCollapseItem: typeof import('./components/collapseitem/collapseitem.vue')['default']
    NutComment: typeof import('./components/comment/comment.vue')['default']
    NutConfigProvider: typeof import('./components/configprovider/configprovider.vue')['default']
    NutCountdown: typeof import('./components/countdown/countdown.vue')['default']
    NutCountup: typeof import('./components/countup/countup.vue')['default']
    NutDatePicker: typeof import('./components/datepicker/datepicker.vue')['default']
    NutDialog: typeof import('./components/dialog/dialog.vue')['default']
    NutDivider: typeof import('./components/divider/divider.vue')['default']
    NutDrag: typeof import('./components/drag/drag.vue')['default']
    NutEcard: typeof import('./components/ecard/ecard.vue')['default']
    NutElevator: typeof import('./components/elevator/elevator.vue')['default']
    NutEllipsis: typeof import('./components/ellipsis/ellipsis.vue')['default']
    NutEmpty: typeof import('./components/empty/empty.vue')['default']
    NutFixedNav: typeof import('./components/fixednav/fixednav.vue')['default']
    NutForm: typeof import('./components/form/form.vue')['default']
    NutFormItem: typeof import('./components/formitem/formitem.vue')['default']
    NutGrid: typeof import('./components/grid/grid.vue')['default']
    NutGridItem: typeof import('./components/griditem/griditem.vue')['default']
    NutIcon: typeof import('./components/icon/icon.vue')['default']
    NutImagePreview: typeof import('./components/imagepreview/imagepreview.vue')['default']
    NutIndicator: typeof import('./components/indicator/indicator.vue')['default']
    NutInfiniteloading: typeof import('./components/infiniteloading/infiniteloading.vue')['default']
    NutInput: typeof import('./components/input/input.vue')['default']
    NutInputNumber: typeof import('./components/inputnumber/inputnumber.vue')['default']
    NutInvoice: typeof import('./components/invoice/invoice.vue')['default']
    NutList: typeof import('./components/list/list.vue')['default']
    NutMenu: typeof import('./components/menu/menu.vue')['default']
    NutMenuItem: typeof import('./components/menuitem/menuitem.vue')['default']
    NutNavbar: typeof import('./components/navbar/navbar.vue')['default']
    NutNoticebar: typeof import('./components/noticebar/noticebar.vue')['default']
    NutNotify: typeof import('./components/notify/notify.vue')['default']
    NutNumberKeyboard: typeof import('./components/numberkeyboard/numberkeyboard.vue')['default']
    NutOverlay: typeof import('./components/overlay/overlay.vue')['default']
    NutPagination: typeof import('./components/pagination/pagination.vue')['default']
    NutPicker: typeof import('./components/picker/picker.vue')['default']
    NutPopover: typeof import('./components/popover/popover.vue')['default']
    NutPopup: typeof import('./components/popup/popup.vue')['default']
    NutPrice: typeof import('./components/price/price.vue')['default']
    NutProgress: typeof import('./components/progress/progress.vue')['default']
    NutRadio: typeof import('./components/radio/radio.vue')['default']
    NutRadioGroup: typeof import('./components/radiogroup/radiogroup.vue')['default']
    NutRange: typeof import('./components/range/range.vue')['default']
    NutRate: typeof import('./components/rate/rate.vue')['default']
    NutRow: typeof import('./components/row/row.vue')['default']
    NutSearchbar: typeof import('./components/searchbar/searchbar.vue')['default']
    NutShortPassword: typeof import('./components/shortpassword/shortpassword.vue')['default']
    NutSideNavbar: typeof import('./components/sidenavbar/sidenavbar.vue')['default']
    NutSideNavbaritem: typeof import('./components/sidenavbaritem/sidenavbaritem.vue')['default']
    NutSideNavbarItem: typeof import('./components/sidenavbaritem/sidenavbaritem.vue')['default']
    NutSignature: typeof import('./components/signature/signature.vue')['default']
    NutSkeleton: typeof import('./components/skeleton/skeleton.vue')['default']
    NutSku: typeof import('./components/sku/sku.vue')['default']
    NutSkuHeader: typeof import('./components/skuheader/skuheader.vue')['default']
    NutSkuOperate: typeof import('./components/skuoperate/skuoperate.vue')['default']
    NutStep: typeof import('./components/step/step.vue')['default']
    NutSteps: typeof import('./components/steps/steps.vue')['default']
    NutSticky: typeof import('./components/sticky/sticky.vue')['default']
    NutSubsideNavbar: typeof import('./components/subsidenavbar/subsidenavbar.vue')['default']
    NutSubSideNavbar: typeof import('./components/subsidenavbar/subsidenavbar.vue')['default']
    NutSwipe: typeof import('./components/swipe/swipe.vue')['default']
    NutSwiper: typeof import('./components/swiper/swiper.vue')['default']
    NutSwiperItem: typeof import('./components/swiperitem/swiperitem.vue')['default']
    NutSwitch: typeof import('./components/switch/switch.vue')['default']
    NutTabbar: typeof import('./components/tabbar/tabbar.vue')['default']
    NutTabbarItem: typeof import('./components/tabbaritem/tabbaritem.vue')['default']
    NutTable: typeof import('./components/table/table.vue')['default']
    NutTabPane: typeof import('./components/tabpane/tabpane.vue')['default']
    NutTabs: typeof import('./components/tabs/tabs.vue')['default']
    NutTag: typeof import('./components/tag/tag.vue')['default']
    NutTextarea: typeof import('./components/textarea/textarea.vue')['default']
    NutTimeDetail: typeof import('./components/timedetail/timedetail.vue')['default']
    NutTimePannel: typeof import('./components/timepannel/timepannel.vue')['default']
    NutTimeSelect: typeof import('./components/timeselect/timeselect.vue')['default']
    NutToast: typeof import('./components/toast/toast.vue')['default']
    NutTour: typeof import('./components/tour/tour.vue')['default']
    NutTransition: typeof import('./components/transition/transition.vue')['default']
    NutTrendArrow: typeof import('./components/trendarrow/trendarrow.vue')['default']
    NutUploader: typeof import('./components/uploader/uploader.vue')['default']
    NutWatermark: typeof import('./components/watermark/watermark.vue')['default']
    NutCodeInput: typeof import('./components/codeinput/codeinput.vue')['default']
    NutDollMachine: typeof import('./components/dollmachine/dollmachine.vue')['default']
    NutGiftBox: typeof import('./components/giftbox/giftbox.vue')['default']
    NutHitEggs: typeof import('./components/hiteggs/hiteggs.vue')['default']
    NutMarquee: typeof import('./components/marquee/marquee.vue')['default']
    NutShakeDice: typeof import('./components/shakedice/shakedice.vue')['default']
    NutTurnTable: typeof import('./components/turntable/turntable.vue')['default']
    NutLoadingPage: typeof import('./components/loadingpage/loadingpage.vue')['default']

  }

  // interface ComponentCustomProperties {}
}

export { }
