export const components = [
  {
    text: '基础组件',
    collapsed: false,
    items: [
      { text: 'Button 按钮', link: '/components/basic/button' },
      { text: 'Cell 单元格', link: '/components/basic/cell' },
      { text: 'ConfigProvider 全局配置', link: '/components/basic/configprovider' },
      { text: 'Icon 图标', link: '/components/basic/icon' },
      { text: 'Overlay 遮照层', link: '/components/basic/overlay' },
      { text: 'Popup 弹出层', link: '/components/basic/popup' },
      { text: 'Transition 过渡', link: '/components/basic/transition' },
    ],
  },
  {
    text: '布局组件',
    collapsed: false,
    items: [
      { text: 'Divider 分割线', link: '/components/layout/divider' },
      { text: 'Grid 宫格', link: '/components/layout/grid' },
      { text: 'Layout 布局', link: '/components/layout/layout' },
      { text: 'SafeArea 安全区', link: '/components/layout/safearea' },
      { text: 'Sticky 粘性布局', link: '/components/layout/sticky' },
    ],
  },
  {
    text: '导航组件',
    collapsed: false,
    items: [
      { text: 'Elevator 电梯楼层', link: '/components/nav/elevator' },
      { text: 'FixedNav 悬浮导航', link: '/components/nav/fixednav' },
      { text: 'Indicator 指示器', link: '/components/nav/indicator' },
      { text: 'Menu 菜单', link: '/components/nav/menu' },
      { text: 'Navbar 头部导航', link: '/components/nav/navbar' },
      { text: 'Pagination 分页', link: '/components/nav/pagination' },
      { text: 'SideNavbar 侧边栏导航', link: '/components/nav/sidenavbar' },
      { text: 'Tabbar 标签栏', link: '/components/nav/tabbar' },
      { text: 'Tabs 选项卡切换', link: '/components/nav/tabs' },

    ],
  },
  {
    text: '数据录入',
    collapsed: false,
    items: [
      { text: 'Calendar 日历', link: '/components/dentry/calendar' },
      { text: 'Cascader 级联选择器', link: '/components/dentry/cascader' },
      { text: 'Checkbox 复选按钮', link: '/components/dentry/checkbox' },
      { text: 'DatePicker 日期选择器', link: '/components/dentry/datepicker' },
      { text: 'Form 表单', link: '/components/dentry/form' },
      { text: 'Input 输入框', link: '/components/dentry/input' },
      { text: 'InputNumber 数字输入框', link: '/components/dentry/inputnumber' },
      { text: 'CodeInput 验证码输入框', link: '/components/dentry/codeinput' },
      { text: 'NumberKeyboard 数字键盘', link: '/components/dentry/numberkeyboard' },
      { text: 'Picker 选择器', link: '/components/dentry/picker' },
      { text: 'Radio 单选按钮', link: '/components/dentry/radio' },
      { text: 'Range 区间选择器', link: '/components/dentry/range' },
      { text: 'Rate 评分', link: '/components/dentry/rate' },
      { text: 'Searchbar 搜索栏', link: '/components/dentry/searchbar' },
      { text: 'ShortPassword 短密码', link: '/components/dentry/shortpassword' },
      { text: 'Textarea 文本域', link: '/components/dentry/textarea' },
      { text: 'Uploader 上传', link: '/components/dentry/uploader' },

    ],
  },
  {
    text: '操作反馈',
    collapsed: false,
    items: [
      { text: 'ActionSheet 动作面板', link: '/components/feedback/actionsheet' },
      { text: 'Backtop 返回顶部', link: '/components/feedback/backtop' },
      { text: 'Dialog 对话框', link: '/components/feedback/dialog' },
      { text: 'Drag 拖拽', link: '/components/feedback/drag' },
      { text: 'Notify 消息通知', link: '/components/feedback/notify' },
      { text: 'Swipe 滑动手势', link: '/components/feedback/swipe' },
      { text: 'Switch 开关', link: '/components/feedback/switch' },
      { text: 'Toast 吐司', link: '/components/feedback/toast' },

    ],
  },
  {
    text: '展示组件',
    collapsed: false,
    items: [
      { text: 'Animate 动画/动效', link: '/components/exhibition/animate' },
      { text: 'Avatar 头像', link: '/components/exhibition/avatar' },
      { text: 'Badge 徽标', link: '/components/exhibition/badge' },
      { text: 'CircleProgress 环形进度条', link: '/components/exhibition/circleprogress' },
      { text: 'Collapse 折叠面板', link: '/components/exhibition/collapse' },
      { text: 'Countdown 倒计时', link: '/components/exhibition/countdown' },
      { text: 'Countup 数字滚动', link: '/components/exhibition/countup' },
      { text: 'Ellipsis 文本省略', link: '/components/exhibition/ellipsis' },
      { text: 'Empty 空状态', link: '/components/exhibition/empty' },
      { text: 'ImagePreview 图片预览', link: '/components/exhibition/imagepreview' },
      { text: 'List 虚拟列表', link: '/components/exhibition/list' },
      { text: 'LoadingPage 加载页', link: '/components/exhibition/loadingpage' },
      { text: 'Noticebar 公告栏', link: '/components/exhibition/noticebar' },
      // { text: 'Popover 气泡弹出框', link: '/components/exhibition/popover' },
      { text: 'Price 价格', link: '/components/exhibition/price' },
      { text: 'Progress 进度条', link: '/components/exhibition/progress' },
      { text: 'Skeleton 骨架屏', link: '/components/exhibition/skeleton' },
      { text: 'Steps 步骤条', link: '/components/exhibition/steps' },
      { text: 'Swiper 轮播', link: '/components/exhibition/swiper' },
      { text: 'Table 表格', link: '/components/exhibition/table' },
      { text: 'Tag 标签', link: '/components/exhibition/tag' },
      // { text: 'Tour 引导', link: '/components/exhibition/tour' },
      { text: 'TrendArrow 趋势箭头', link: '/components/exhibition/trendarrow' },
      { text: 'Watermark 水印', link: '/components/exhibition/watermark' },
    ],
  },
  {
    text: '特色组件',
    collapsed: false,
    items: [
      { text: 'Address 地址', link: '/components/business/address' },
      { text: 'AddressList 地址列表', link: '/components/business/addresslist' },
      { text: 'Barrage 弹幕', link: '/components/business/barrage' },
      { text: 'Card 商品卡片', link: '/components/business/card' },
      { text: 'Category 商品分类', link: '/components/business/category' },
      { text: 'Comment 商品评论', link: '/components/business/comment' },
      { text: 'Ecard 虚拟电子卡', link: '/components/business/ecard' },
      { text: 'Invoice 发票', link: '/components/business/invoice' },
      { text: 'Signature 签名', link: '/components/business/signature' },
      { text: 'Sku 商品规格选择', link: '/components/business/sku' },
      { text: 'TimeSelect 配送时间', link: '/components/business/timeselect' },
    ],
  },
  {
    text: '抽奖组件',
    collapsed: false,
    items: [
      { text: 'TurnTable 大转盘抽奖', link: '/components/bingo/turntable' },
      { text: 'Marquee 跑马灯抽奖', link: '/components/bingo/marquee' },
      { text: 'GiftBox 神秘大礼盒', link: '/components/bingo/giftbox' },
      { text: 'Hiteggs 砸金蛋', link: '/components/bingo/hiteggs' },
      { text: 'DollMachine 抓娃娃机', link: '/components/bingo/dollmachine' },
      { text: 'ShakeDice 摇骰子', link: '/components/bingo/shakedice' },
    ],
  },
]

export const navComponents = components.map(i => ({ text: i.text, link: i.items[0].link }))

export const guides = [
  { text: '概览', link: '/guide/overview' },
  { text: '快速上手', link: '/guide/quick-start' },
  { text: '国际化', link: '/guide/i18n' },
  { text: '定制主题', link: '/guide/theme' },
  { text: '注意事项', link: '/guide/faq' },
  { text: '更新日志', link: '/guide/changelog' },
]
