/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by vite-plugin-uni-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    DemoHeader: typeof import('./components/DemoHeader.vue')['default']
    ThemeSwitch: typeof import('./components/ThemeSwitch.vue')['default']
  }
}
