/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by vite-plugin-uni-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    NutButton: typeof import('uniapp-nutui/components/button/button.vue')['default']
    NutConfigProvider: typeof import('uniapp-nutui/components/configprovider/configprovider.vue')['default']
    NutCountdown: typeof import('uniapp-nutui/components/countdown/countdown.vue')['default']
    NutIcon: typeof import('uniapp-nutui/components/icon/icon.vue')['default']
  }
}
