/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by vite-plugin-uni-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    DemoHeader: typeof import('./components/DemoHeader.vue')['default']
    NutAddress: typeof import('uniapp-nutui/components/address/address.vue')['default']
    NutAddressList: typeof import('uniapp-nutui/components/addresslist/addresslist.vue')['default']
    NutAvatar: typeof import('uniapp-nutui/components/avatar/avatar.vue')['default']
    NutBadge: typeof import('uniapp-nutui/components/badge/badge.vue')['default']
    NutButton: typeof import('uniapp-nutui/components/button/button.vue')['default']
    NutCalendar: typeof import('uniapp-nutui/components/calendar/calendar.vue')['default']
    NutCascader: typeof import('uniapp-nutui/components/cascader/cascader.vue')['default']
    NutCell: typeof import('uniapp-nutui/components/cell/cell.vue')['default']
    NutCellGroup: typeof import('uniapp-nutui/components/cellgroup/cellgroup.vue')['default']
    NutCheckbox: typeof import('uniapp-nutui/components/checkbox/checkbox.vue')['default']
    NutCheckboxGroup: typeof import('uniapp-nutui/components/checkboxgroup/checkboxgroup.vue')['default']
    NutConfigProvider: typeof import('uniapp-nutui/components/configprovider/configprovider.vue')['default']
    NutDatePicker: typeof import('uniapp-nutui/components/datepicker/datepicker.vue')['default']
    NutForm: typeof import('uniapp-nutui/components/form/form.vue')['default']
    NutFormItem: typeof import('uniapp-nutui/components/formitem/formitem.vue')['default']
    NutIcon: typeof import('uniapp-nutui/components/icon/icon.vue')['default']
    NutInputNumber: typeof import('uniapp-nutui/components/inputnumber/inputnumber.vue')['default']
    NutNavbar: typeof import('uniapp-nutui/components/navbar/navbar.vue')['default']
    NutPopup: typeof import('uniapp-nutui/components/popup/popup.vue')['default']
    NutRadio: typeof import('uniapp-nutui/components/radio/radio.vue')['default']
    NutRadioGroup: typeof import('uniapp-nutui/components/radiogroup/radiogroup.vue')['default']
    NutRange: typeof import('uniapp-nutui/components/range/range.vue')['default']
    NutRate: typeof import('uniapp-nutui/components/rate/rate.vue')['default']
    NutRow: typeof import('uniapp-nutui/components/row/row.vue')['default']
    NutSwitch: typeof import('uniapp-nutui/components/switch/switch.vue')['default']
    NutToast: typeof import('uniapp-nutui/components/toast/toast.vue')['default']
    NutUploader: typeof import('uniapp-nutui/components/uploader/uploader.vue')['default']
    ThemeSwitch: typeof import('./components/ThemeSwitch.vue')['default']
  }
}
